version: "3.5"
services:
  frontend:
    image: frontend
    build: ./frontend
    depends_on:
      - backend
  backend:
    image: backend
    build: ./backend
    depends_on:
      - mysql
  nginx:
    image: nginx:latest
    ports:
    - target: 80
      published: 80
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf
    depends_on:
      - frontend
  mysql:
    image: database
    build: ./database
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=database
